USE [master]
GO
/****** Object:  Database [SmartERP]    Script Date: 06.09.2024 17:31:25 ******/
CREATE DATABASE [SmartERP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartERP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SmartERP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmartERP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SmartERP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SmartERP] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartERP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SmartERP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SmartERP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SmartERP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SmartERP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SmartERP] SET ARITHABORT OFF 
GO
ALTER DATABASE [SmartERP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SmartERP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SmartERP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SmartERP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SmartERP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SmartERP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SmartERP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SmartERP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SmartERP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SmartERP] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SmartERP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SmartERP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SmartERP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SmartERP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SmartERP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SmartERP] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [SmartERP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SmartERP] SET RECOVERY FULL 
GO
ALTER DATABASE [SmartERP] SET  MULTI_USER 
GO
ALTER DATABASE [SmartERP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SmartERP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SmartERP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SmartERP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SmartERP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SmartERP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SmartERP', N'ON'
GO
ALTER DATABASE [SmartERP] SET QUERY_STORE = ON
GO
ALTER DATABASE [SmartERP] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SmartERP]
GO
/****** Object:  Schema [development]    Script Date: 06.09.2024 17:31:25 ******/
CREATE SCHEMA [development]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 06.09.2024 17:31:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [development].[CustomEntities]    Script Date: 06.09.2024 17:31:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [development].[CustomEntities](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ModuleId] [bigint] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[DisplayName] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CustomEntities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [development].[CustomEntityFields]    Script Date: 06.09.2024 17:31:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [development].[CustomEntityFields](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[EntityId] [bigint] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[DisplayName] [nvarchar](max) NOT NULL,
	[Type] [nvarchar](max) NOT NULL,
	[IsRequired] [bit] NOT NULL,
 CONSTRAINT [PK_CustomEntityFields] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [development].[CustomModules]    Script Date: 06.09.2024 17:31:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [development].[CustomModules](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[DisplayName] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CustomModules] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [development].[CustomViews]    Script Date: 06.09.2024 17:31:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [development].[CustomViews](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ModuleId] [bigint] NOT NULL,
 CONSTRAINT [PK_CustomViews] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_CustomEntities_ModuleId]    Script Date: 06.09.2024 17:31:25 ******/
CREATE NONCLUSTERED INDEX [IX_CustomEntities_ModuleId] ON [development].[CustomEntities]
(
	[ModuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CustomEntityFields_EntityId]    Script Date: 06.09.2024 17:31:25 ******/
CREATE NONCLUSTERED INDEX [IX_CustomEntityFields_EntityId] ON [development].[CustomEntityFields]
(
	[EntityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CustomViews_ModuleId]    Script Date: 06.09.2024 17:31:25 ******/
CREATE NONCLUSTERED INDEX [IX_CustomViews_ModuleId] ON [development].[CustomViews]
(
	[ModuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [development].[CustomEntities]  WITH CHECK ADD  CONSTRAINT [FK_CustomEntities_CustomModules_ModuleId] FOREIGN KEY([ModuleId])
REFERENCES [development].[CustomModules] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [development].[CustomEntities] CHECK CONSTRAINT [FK_CustomEntities_CustomModules_ModuleId]
GO
ALTER TABLE [development].[CustomEntityFields]  WITH CHECK ADD  CONSTRAINT [FK_CustomEntityFields_CustomEntities_EntityId] FOREIGN KEY([EntityId])
REFERENCES [development].[CustomEntities] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [development].[CustomEntityFields] CHECK CONSTRAINT [FK_CustomEntityFields_CustomEntities_EntityId]
GO
ALTER TABLE [development].[CustomViews]  WITH CHECK ADD  CONSTRAINT [FK_CustomViews_CustomModules_ModuleId] FOREIGN KEY([ModuleId])
REFERENCES [development].[CustomModules] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [development].[CustomViews] CHECK CONSTRAINT [FK_CustomViews_CustomModules_ModuleId]
GO
USE [master]
GO
ALTER DATABASE [SmartERP] SET  READ_WRITE 
GO
